[package]
name = "rings"
version = "0.1.0"
edition = "2024"

[dependencies]
index_vec = "0.1.4"
interavl = "0.5.0"

[features]
record=[]
procedures=[]
table=[]
index=[]
forloop=[]
call=[]
optimize=[]
types=[]
notes=[]
